NAME: 'dist_b4_bmls30_accv_224'
OUTPUT_DIR: '/home/432/qihaoyu/data/accv/results'
SHOW_STEP: 1
SAVE_STEP: 5
VALID_STEP: -1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'iNaturalist'
  DATA_TYPE: 'jpg'
  TRAIN_JSON: '/home/432/qihaoyu/vscode_workspace/accv_cls/clean_train.json'
  VALID_JSON: '/home/432/qihaoyu/vscode_workspace/accv_cls/test.json'

BACKBONE:
  TYPE: 'efficient_b4'
  # PRETRAINED_MODEL: '/home/432/qihaoyu/vscode_workspace/accv_cls/b4_labelsmooth_mixup_epoch30_res224.pth'

MODULE:
  TYPE: 'GAP'

LOSS:
  LOSS_TYPE: 'CrossEntropyLabelSmooth'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

TRAIN:
  BATCH_SIZE: 64
  MAX_EPOCH: 30
  NUM_WORKERS: 0
  COMBINER:
    TYPE: 'mix_up'
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.05
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'cosine'

    # LR_STEP: [20, 25]
    # LR_FACTOR: 0.1
    # WARM_EPOCH: 5
  DISTRIBUTED: True
  SYNCBN: True
  # COTEACHING: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 16
  MODEL_FILE: '/home/432/qihaoyu/vscode_workspace/accv_cls/b4_labelsmooth_mixup_epoch30_res224.pth'

