NAME: 'dist_r50_10_chestRayNIH_auc.yaml'
OUTPUT_DIR: '/home/432/qihaoyu/data/ChestRay_exp/baseline_NIH/BCElosswithlogits'
SHOW_STEP: 1
SAVE_STEP: 1
VALID_STEP: 1
INPUT_SIZE: (1024, 1024)
CPU_MODE: False
COLOR_SPACE: GRAYSCALE

DATASET:
  DATASET: 'ChestRayNIH'
  DATA_TYPE: 'png'
  TRAIN_JSON: '/home/432/qihaoyu/vscode_workspace/accv_cls/ChestRayNIH-train.json'
  VALID_JSON: '/home/432/qihaoyu/vscode_workspace/accv_cls/ChestRayNIH-test.json'

LOSS:
  LOSS_TYPE: 'BCEWithLogitsLoss'

MODULE:
  TYPE: 'GAP'

BACKBONE:
  TYPE: 'res50'
  PRETRAINED_MODEL: ""

TRAIN:
  BATCH_SIZE: 16
  MAX_EPOCH: 10
  NUM_WORKERS: 10
  SHUFFLE: True
  METRIC: 'auc'
  COMBINER:
    TYPE: 'multi_label'
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: False
      TYPE: 'reverse'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 1e-4
    MOMENTUM: 0.9
  LR_SCHEDULER:
    TYPE: 'cosine'
  DISTRIBUTED: True
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop",)
  TEST_TRANSFORMS: ("center_crop",)