NAME: 'dist_rs200_bmls120_icpr'
OUTPUT_DIR: '/data/output/icpr'
SHOW_STEP: 50
SAVE_STEP: 5
VALID_STEP: -1
INPUT_SIZE: (320, 320)
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'iNaturalist'
  DATA_TYPE: 'nori'
  TRAIN_JSON: '/data/dataset/ICPR/bbn_icpr_train_nori.json'
  VALID_JSON: '/data/dataset/ICPR/bbn_icpr_train_nori.json'

BACKBONE:
  TYPE: 'resnest200_b'
  PRETRAINED_MODEL: '/home/zhaobingchen/.torch/models/resnest200.pth'

MODULE:
  TYPE: 'GAP'

LOSS:
  LOSS_TYPE: 'CrossEntropyLabelSmooth'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

TRAIN:
  BATCH_SIZE: 16
  MAX_EPOCH: 120
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'mix_up'
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.05
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'cosine'

    # LR_STEP: [20, 25]
    # LR_FACTOR: 0.1
    # WARM_EPOCH: 5
  DISTRIBUTED: True
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 16
  MODEL_FILE: '/home/BBN/models/BBN.iNaturalist2019.res50.180epoch.best_model.pth'

